### ISSUE TITLE
Adicionar informações do repositório com o js

### ISSUE THREAD

**Issue by gabsdocompiuter** [gmonteeeiro/github-portfolio#9]
Ajustar JavaScript para mostrar as seguintes informações dos repositórios:

- [x] `name` Nome do repositório
- [x] `description` Descrição do repositório
- [x] `language` Linguagem usada para desenvolver o repositório
- [x] `stargazers_count` Quantidade de estrelas
- [x] `forks_count` Quantidade de Foks
- [x] `fork` É um fork ou não?

**Comment by gmonteeeiro** [comment]
Informações do repositório que serão utilizadas:

- [ ] `name` Nome do repositório
- [ ] `description` Descrição do repositório
- [ ] `language` Linguagem usada para desenvolver o repositório
- [ ] `stargazers_count` Quantidade de estrelas
- [ ] `forks_count` Quantidade de Foks
- [ ] `fork` É um fork ou não?
